### ISSUE TITLE
Welcome to GitHub JasonEtco!

### ISSUE THREAD

**Issue by githubteacher** [training-app-org/welcome-JasonEtco#1]
### Welcome!

Hello :wave:, I’m Teacherbot, a friendly robot :robot: who is going to help you learn about Git and GitHub. This is an Issue, and although you won’t be using them very often in your day-to-day work at Salesforce I will be using them to guide you through the activities.

For now, show me your favorite emoji by making a comment below. You can search for emoji by typing a `:` and typing a word you want an emoji for. For example I :heart: using the `:gear:` emoji. After picking an emoji click the **Comment** button.

While you are adding a comment with your favorite emoji, it might be a good time to assign this issue to yourself. Typically, the “Assignees” section helps other contributors identify who is responsible for completing a task. Clicking `assign yourself` under the Assignees section will automatically add you to the Assignees section.

![issue assignment](https://proteacher-dotcom.herokuapp.com/img/issue-assignment.png)

**Comment by JasonEtco** [comment]
🍕

**Comment by githubteacher** [comment]
Hey! That is an awesome emoji! Now that we can communicate, let's talk a little about branches.

### :bookmark: Informational content

Whenever I'm going to provide some contextual information I will use the :bookmark: emoji to identify that you need to go to the course manual: https://proteacher-production.herokuapp.com/manual/

### :woman_technologist: Actionable items

Whenever I'm asking you to do something, I'll start my comments with the :woman_technologist: laptop emoji.

### :robot: Actions I can check for you

Sometimes, I can check your work. When I am waiting for you to do something I can check, I'll end my comments with the :robot: robot emoji.

There are some things I can't check, like the work you do locally on your machine (without sending that work to GitHub). In those cases, I'll tell you what you need to do, and assume you've done it.

**Comment by githubteacher** [comment]
### :woman_technologist: Create a branch

At Salesforce you are most likely going to be creating work or feature branches from the release branch. As it just so happens, this repository also has a master and release branch.

To create your first branch you are going to be using the Code tab. On the Code tab, there is a drop-down that has `Branch: master` in it. Before creating a new branch, look at the files found in the `master` branch.

![branch drop down](https://proteacher-dotcom.herokuapp.com/img/branch-drop-down.png)

Click the drop-down and select the `release_SFtraining` branch. After selecting the `release` branch, take a look at the files on the branch. Notice anything new? For this class we added a file called “release.md” to show you that the branches can contain different files (or more importantly, different points in history). While on the `release_SFtraining` branch, click the branch drop-down again. In the `Find or create a branch…` field, enter `work_username` where `username` is your username. For example, `work_teacherbot` would be my branch.

![creating a branch](https://proteacher-dotcom.herokuapp.com/img/creating-a-branch.png)

Notice when you create the branch, it says it is “from `release_SFtraining`". That means your branch is based off of the `release_SFtraining` branch as opposed to the `master` branch.

:robot: I'm waiting for you to create a branch. I'll respond when I detect a new branch.

**Comment by githubteacher** [comment]
### :woman_technologist: Great!

This issue is now closed. 

:bookmark: Now that you have a branch, go back to the manual and learn about the Salesforce workflow and how to create a commit before getting back to some hands on exercises.
